server:
  port: 8080
spring:
  datasource:
    #1.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dim_light_dream?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: ewq18740000
springdoc:
  swagger-ui:
    path: /swagger-ui